'use strict';

// Plan -> TikZ source. Keeps generated figures readable to a researcher
// familiar with LaTeX: plain \node / \draw / \fill, semantic node names, no
// opaque DSL.

const { texEscape } = require('../../beamer/renderTex');
const { roleColor, roleFill } = require('./styles');

function escapeLabel(value) {
  const s = value === null || value === undefined ? '' : String(value);
  let out = '';
  let i = 0;
  while (i < s.length) {
    const start = s.indexOf('$', i);
    if (start === -1) { out += texEscape(s.slice(i)); break; }
    const end = s.indexOf('$', start + 1);
    if (end === -1) { out += texEscape(s.slice(i)); break; }
    out += texEscape(s.slice(i, start)) + s.slice(start, end + 1);
    i = end + 1;
  }
  return out;
}

function fmt(n) {
  return Number(n).toFixed(2).replace(/\.00$/, '').replace(/(\.\d)0$/, '$1');
}

function nodeTex(n) {
  const label = escapeLabel(n.label);
  const head = `  \\node[${n.style}, draw=${n.draw}, fill=${n.fill}, align=center] (${n.name}) at (${fmt(n.x)}, ${fmt(n.y)}) {${label}};`;
  if (!n.detail) return head;
  // Feature circles stay compact: the detail goes below the node, not inside.
  if (n.style === 'methodFeature') {
    return `${head}\n  \\node[below=0.04cm of ${n.name}, font=\\scriptsize, text=wrsMuted, align=center] {${escapeLabel(n.detail)}};`;
  }
  return `  \\node[${n.style}, draw=${n.draw}, fill=${n.fill}, align=center] (${n.name}) at (${fmt(n.x)}, ${fmt(n.y)}) {${label}\\\\[0.3mm]{\\scriptsize\\color{wrsMuted}${escapeLabel(n.detail)}}};`;
}

function edgeTex(e) {
  const label = e.label
    ? ` node[midway, ${e.labelSide || 'above'}, font=\\scriptsize, text=wrsInkSoft, fill=white, inner sep=1pt] {${escapeLabel(e.label)}}`
    : '';
  if (e.feedback) {
    return `  \\draw[${e.style}] (${e.from}) to[out=-65, in=-115, looseness=1.15]${label} (${e.to});`;
  }
  return `  \\draw[${e.style}] (${e.from}) --${label} (${e.to});`;
}

function stageTex(s) {
  const role = s.role || 'shared';
  return [
    '  \\begin{scope}[on background layer]',
    `    \\draw[draw=${roleColor(role)}, fill=${roleFill(role)}] (${fmt(s.x0)}, ${fmt(s.y0)}) rectangle (${fmt(s.x1)}, ${fmt(s.y1)});`,
    '  \\end{scope}',
    `  \\node[methodStageLabel] at (${fmt((s.x0 + s.x1) / 2)}, ${fmt(s.headerY)}) {${escapeLabel(s.label)}};`,
  ].join('\n');
}

function arcTex(a) {
  const rad = (deg) => (deg * Math.PI) / 180;
  const lx = a.cx + Math.cos(rad(a.labelAngle)) * a.labelR;
  const ly = a.cy + Math.sin(rad(a.labelAngle)) * a.labelR;
  return [
    `  \\draw[methodDimension] (${fmt(a.cx)}, ${fmt(a.cy)}) ++(${fmt(a.start)}:${fmt(a.r)}) arc[start angle=${fmt(a.start)}, end angle=${fmt(a.end)}, radius=${fmt(a.r)}];`,
    `  \\node[font=\\scriptsize, text=wrsMuted] at (${fmt(lx)}, ${fmt(ly)}) {${escapeLabel(a.label)}};`,
  ].join('\n');
}

function noteTex(n) {
  return `  \\node[methodNote, anchor=${n.anchor || 'center'}] at (${fmt(n.x)}, ${fmt(n.y)}) {${escapeLabel(n.text)}};`;
}

function legendTex(plan) {
  if (!plan.legend || !plan.legend.length) return '';
  const xs = plan.nodes.map((n) => n.x);
  const nodeTops = plan.nodes.map((n) => n.y - (n.style === 'methodFeature' ? 0.55 : 0.5));
  const stageTops = (plan.stages || []).map((s) => s.y0);
  const x0 = Math.min(...xs);
  const y0 = Math.min(...nodeTops, ...stageTops) - 0.55;
  const lines = ['  \\begin{scope}[every node/.append style={font=\\scriptsize}]'];
  plan.legend.forEach((entry, i) => {
    const x = x0 + i * 2.9;
    lines.push(`    \\node[methodFeature, minimum size=2.6mm, inner sep=0pt, draw=${roleColor(entry.role)}, fill=${roleColor(entry.role)}] (legend-${i}) at (${fmt(x)}, ${fmt(y0)}) {};`);
    lines.push(`    \\node[anchor=west, text=wrsMuted] at ([xshift=2.4mm]legend-${i}.east) {${escapeLabel(entry.label)}};`);
  });
  lines.push('  \\end{scope}');
  return lines.join('\n');
}

function revealTex(index, code) {
  if (!index || index <= 1) return code;
  return `  \\wrsReveal{${index}}{%\n${code}\n  }`;
}

function planToTex(plan, opts = {}) {
  const decision = opts.decision || null;
  const spec = opts.spec || {};
  const fig = spec.figure || {};
  const header = [
    '% Generated by weekly-research-slides (native TikZ backend).',
    `% figure: ${fig.id || 'figure'} (${fig.type || 'unknown'}${fig.mode ? `, ${fig.mode}` : ''})`,
  ];
  if (decision) header.push(`% renderer_decision: selected=${decision.selected}; reason=${decision.reason.join('; ')}`);
  const semanticIds = (plan.nodes || [])
    .filter((n) => n.semantic && n.semantic !== n.id)
    .map((n) => `${n.name}=${n.semantic}`);
  if (semanticIds.length) header.push(`% semantic ids: ${semanticIds.join(' ')}`);
  const lines = [header.join('\n'), '\\begin{tikzpicture}[x=1cm,y=1cm]'];
  (plan.stages || []).forEach((s) => lines.push(stageTex(s)));
  // Nodes first: TikZ resolves node names when an edge is drawn.
  (plan.nodes || []).forEach((n) => lines.push(revealTex(n.reveal, nodeTex(n))));
  (plan.edges || []).forEach((e) => lines.push(revealTex(e.reveal, edgeTex(e))));
  (plan.arcs || []).forEach((a) => lines.push(arcTex(a)));
  (plan.notes || []).forEach((n) => lines.push(noteTex(n)));
  const legend = legendTex(plan);
  if (legend) lines.push(legend);
  lines.push('\\end{tikzpicture}');
  return `${lines.join('\n')}\n`;
}

module.exports = { planToTex, escapeLabel, fmt };
